
#LINUX_KERNEL_PATH := /data/lym/Hi3516EV200_SDK_V1.0.1.3/osdrv/opensource/kernel/linux-4.9.y
#LINUX_KERNEL_PATH := /data/lxc/V10C/linux-4.9.y

#LINUX_KERNEL_PATH := /home/cwj/data_ext/hi3516ev300_kernel_1.3.0/kernel/linux-4.9.y
#CROSS_COMPILE=arm-himix100-linux-

#LINUX_KERNEL_PATH := /data_ext/cwj/GK7205V300/GKIPCLinuxV100R001C00SPC020/out/gk7205v300/linux-4.9.y

#LINUX_KERNEL_PATH := /home/cwj/data_ext/ssd268g_super_sound/kernel
#CROSS_COMPILE=arm-linux-gnueabihf-sigmastar-9.1.0-

LINUX_KERNEL_PATH := /data_ext/cwj/NT98530_SDK_Package/na51102_linux_sdk/BSP/linux-kernel
CROSS_COMPILE=aarch64-ca53-linux-gnu-

